version: "3"
services:
  influxdb:
    image: influxdb:latest
    environment:
      INFLUXDB_DB: "speedtest"
    volumes:
      - "/store/tmp/speedtest-influx-data:/var/lib/influxdb"
  grafana:
    build: .
    image: grafana/grafana:latest
    ports:
      - "9000:3000"
    volumes:
      - "/store/tmp/speedtest-grafana-data:/var/lib/grafana"
      - "./speedtest.yml:/etc/provisioning/datasources/speedtest.yml"
      - "./multipanel.json:/usr/share/grafana/public/dashboards/home.json"
      - "./grafana.ini:/etc/grafana/grafana.ini"
  speedtest:
    build: .
    image: ckzed-speedtest:latest
