version: "3"
services:
  influxdb:
    image: influxdb:latest
    environment:
      INFLUXDB_DB: "speedtest"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "9000:3000"
  speedtest:
    build: .
    image: ckzed-speedtest:latest
